language: node_js

node_js:
- "8"

env:
  global:
  - OPAM_LINUX_URL=https://github.com/ocaml/opam/releases/download/2.0.4/opam-2.0.4-x86_64-linux

cache:
  apt: true
  directories:
  - /usr/local/Homebrew
  - $HOME/.opam

matrix:
  include:
  - os: linux
    env: FAKE_ARCH=32
  - os: osx
    env: FAKE_ARCH=64

addons:
  apt:
    packages:
    - opam
  homebrew:
    update: true
    packages:
    - opam

before_cache:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cleanup; fi

install:
- echo $TRAVIS_OS_NAME
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    sudo curl -sL $OPAM_LINUX_URL -o /usr/bin/opam &&
    sudo chmod 755 /usr/bin/opam; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew info opam; fi

script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then lsb_release -a; fi
- opam --version
- node -v
- echo $FAKE_ARCH
